'use strict';

// DB must be fixed after editing this.

module.exports = {
  ACCESS_ADMIN_PANEL: 'ACCESS_ADMIN_PANEL',
  ADD_REMOVE_ROLE: 'ADD_REMOVE_ROLE',
  GRANT_REVOKE_ROLE: 'GRANT_REVOKE_ROLE',
  GET_ROLE: 'GET_ROLE',
  GET_ROLE_LIST: 'GET_ROLE_LIST',
  SET_PERMISSION_OF_ROLE: 'SET_PERMISSION_OF_ROLE',
  SET_ARTICLE_PERMISSION: 'SET_ARTICLE_PERMISSION',
  SET_SITE_NOTICE: 'SET_SITE_NOTICE',
  SET_FRONT_PAGE: 'SET_FRONT_PAGE',
  SET_WIKI_NAME: 'SET_WIKI_NAME',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_NAMESPACE: 'SET_NAMESPACE',
  SET_LICENSE: 'SET_LICENSE',
  GET_USER_LIST: 'GET_USER_LIST',
  SET_EMAIL: 'SET_EMAIL',
  BLOCK: 'BLOCK',
  SET_DISCUSSION_STATUS: 'SET_DISCUSSION_STATUS',
};
