'use strict';

module.exports = {
  ACCESS_ADMIN_PANEL: 'ACCESS_ADMIN_PANEL',
  GET_ROLE: 'GET_ROLE',
  GET_ROLE_LIST: 'GET_ROLE_LIST',
  SET_PERMISSION_OF_ROLE: 'SET_PERMISSION_OF_ROLE',
  SET_SITENOTICE: 'SET_SITENOTICE',
  SET_NAMESPACE: 'SET_NAMESPACE',
  GET_USER_LIST: 'GET_USER_LIST',
  SET_USER_ROLE: 'SET_USER_ROLE',
};
