'use strict';

module.exports = {
  ACCESS_ADMIN_PANEL: 'ACCESS_ADMIN_PANEL',
  VIEW_ROLES: 'VIEW_ROLES',
  CHANGE_PERMISSION_OF_ROLE: 'CHANGE_PERMISSION_OF_ROLE',
  EDIT_SITENOTICE: 'EDIT_SITENOTICE',
  GET_USER_LIST: 'GET_USER_LIST',
};
